#!/bin/bash
# (c) Copyright 2015 by Martin Meier, Emplstr. 20, 81829 München, Germany
# Licensed under MIT License (see LICENSE)
#
# purpose: create a simple HTML status page of a bitcoin node

# get dir of current script
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# configuration
# assume groestlcoind-cli is located in /usr/local/bin, adjust PATH if it is located elsewhere
PATH=$PATH:/usr/local/bin
templatefile=$DIR/status.template.html
outputdir=~/docroot
IP=148.251.6.18

# get status of groestlcoin daemon as bash variables
eval `groestlcoin-cli getnetworkinfo | head -n -1 | tail -n +2 | sed -e 's/\s*\"\([^"]*\)\" : \([^\,]*\).*/\1=\2/'`
eval `groestlcoin-cli getblockchaininfo | head -n -1 | tail -n +2 | sed -e 's/\s*\"\([^"]*\)\" : \([^\,]*\).*/\1=\2/'`

# fill the template and store it in index.html
echo "$(eval "echo \"$(cat $templatefile)\"")" > $outputdir/index.html
cp $qr_image $outputdir/
